### ISSUE TITLE
Submission Doesn't Work

### ISSUE THREAD

**Issue by lolidkstudio** [HAHSTechClub/tmcw-submission#1]
Hello,

One of my friends from Hurlstone showed me this website. They had got the answer for one of the problems, but every time they submitted, the thing would be incorrect. They tried using different punctuation and capitalisation, but it didn't work.

I think the reason for this is that on both the front and backend, i couldn't find any occurrence of the `.trim()` function, which could possibly indicate that if there is some accidental whitespace in the google sheet cells, the code would not be compared properly.

Kind regards, lolidk0088

**Comment by UtsavK-0112** [comment]
Hi, thanks for bringing up the issue. There were no whitespace in the sheet answer cells, but there WAS a typo in the answer. It should be fixed now 👍.

**Comment by UtsavK-0112** [comment]
Hey btw did you go the UNSW CompClub workshop last year by chance?

**Comment by lolidkstudio** [comment]
I didn't go to the UNSW CompClub workshop last year. if you're thinking of someone it's not me, but I searched it up and it does sound cool.

**Comment by UtsavK-0112** [comment]
Oh, there was someone there from SBHS that made their tabletable website there and I thought it might be you. I do apologise for making you go through that hacked together mess of code, it was definitely not my best work.

**Comment by lolidkstudio** [comment]
No worries. There are multiple people at SBHS who have made timetable apps, but if [this](https://www.timetabl.app) is the one you're talking about, I know the dev.
